# Generated by Django 4.1.5 on 2023-01-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('ingredients', models.CharField(default='', max_length=300)),
                ('recipe', models.TextField(default='', max_length=1000)),
                ('post_date', models.DateTimeField()),
                ('difficulty_1_10', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dish_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='recipes.dishcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
