# Generated by Django 4.1.5 on 2023-01-19 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_dish_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='difficulty_1_10',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
